version: '3'
services:
  db-v1-posts:
    image: postgres
    environment:
      POSTGRES_DB: "db-v1-posts"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
       - '15432:5432'
#    links:
#      - v1-posts
  db-admin-v1-posts:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "xpto@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2020!"
    ports:
      - '16543:80'
    depends_on:
     - db-v1-posts
#  v1-posts:
#    restart: on-failure
#    build:
#      context: ./posts/
#      dockerfile: ./Dockerfile
#    ports:
#      - '8081:8081'
#    environment:
#      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
#      - PROFILE=dev