pipeline {
    agent any
	tools {
		maven '3.6.3'
	}
    environment { 
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -version'
                sh 'cd posts/; mvn clean install'
            }
            post {
                always {
                    cleanWs()
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Dtest=br.com.posts.** test' 
            }
        }
    }
}