pipeline {
    agent any
	tools {
		maven '3.6.3'
	}
    environment { 
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -version'
                sh 'cd posts/; mvn clean install'
            }
        }
        // stage('Test') {
        //     steps {
        //         sh 'cd posts/; mvn -Dtest=br.com.posts.** test' 
        //     }
        //     post {
        //         always {
        //             cleanWs()
        //         }
        //     }
        // }
        stage('Deliver') {
            steps {
                sh 'ls'
                sh 'docker-compose up -d' 
            }
        }
    }
}